# endorsed-config.yaml
# VERSION 1.0.0

#------------------------
# Authentication Domains \
#------------------------------------------------------------------------------
# This section defines where user authentication will
# occur.
auth: 
  uri: "https://auth.openshift.io"

#-----------------------
# Github Authentication \
#------------------------------------------------------------------------------
# This section defines github authentication
github: 
    clientID: ""
    clientSecret: ""

#-----------------------
# Sentry Authentication \
#------------------------------------------------------------------------------
# This section defines sebtry authentication
sentry:
    dsn: ""

#---------------------------
# Rest API Configuration    \
#------------------------------------------------------------------------------
# This section defines the url used by swagger to create the rest-api.
server:
  host: "localhost"
  port: 8099